version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    groups:
      dev-dependencies:
        dependency-type: 'development'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react*'
