// ── Access levels ──────────────────────────────────────────
export type AccessLevel = 'none' | 'user' | 'admin' | 'root';

// ── Relationship ───────────────────────────────────────────
export type Relationship = 'unknown' | 'neutral' | 'cooperative' | 'ally' | 'hostile';

const ACCESS_RANK: Record<AccessLevel, number> = {
  none: 0,
  user: 1,
  admin: 2,
  root: 3,
};

export const hasAccess = (have: AccessLevel, need: AccessLevel): boolean => {
  return ACCESS_RANK[have] >= ACCESS_RANK[need];
};

// ── Network ────────────────────────────────────────────────
export const NODE_TEMPLATES = [
  'workstation',
  'database_server',
  'file_server',
  'web_server',
  'security_node',
  'mail_server',
  'iot_device',
  'router_switch',
  'printer',
  'dev_server',
] as const;

export type NodeTemplate = (typeof NODE_TEMPLATES)[number];

/** An instantiated node created from a template, before it enters live runtime state. */
export interface NodeInstance {
  nodeId: string;
  templateId: NodeTemplate;
  label: string;
  layer: number;
  division?: string;
  anchor: boolean;
}

export type FileType =
  | 'log'
  | 'document'
  | 'credential'
  | 'config'
  | 'email'
  | 'binary'
  | 'tripwire';

export interface GameFile {
  name: string;
  path: string;
  type: FileType;
  content: string | null; // null = pending AI generation (Phase 3)
  exfiltrable: boolean;
  accessRequired: AccessLevel;
  ariaPlanted?: boolean;
  tripwire?: boolean; // reading costs +25 trace
  traceOnRead?: number; // 1–3 extra trace added when cat'd (non-tripwire files); omit or 0 = no extra cost
  locked?: boolean; // set at 31% threshold; blocks cat and exfil
  deleted?: boolean; // set by sentinel after 3-turn delay post-exfil
  planted?: boolean; // dynamically added at runtime (e.g. sentinel RESET_NOTICE); persisted in full
}

export interface Service {
  name: string;
  port: number;
  vulnerable: boolean;
  exploitCost: number; // charges consumed
  accessGained: AccessLevel; // what you get on success
  patched?: boolean; // sentinel can set this
  traceContribution?: number; // trace added on successful exploit (0 = clean/silent)
}

export interface LiveNode {
  id: string;
  ip: string;
  template: NodeTemplate;
  label: string; // short display name
  description: string | null; // flavour text shown on connect; null = pending AI generation (filler nodes)
  flavourDescription?: string; // authored atmospheric text shown on connect for anchor nodes; replaces description when present
  layer: number; // 0=entry, 1=ops, 2=sec, 3=fin, 4=exec, 5=aria
  anchor: boolean;
  ariaInfluence?: number; // 0–1, how much Aria has shaped this node (Phase 4+)
  connections: string[]; // node IDs reachable from here
  services: Service[];
  files: GameFile[];
  accessLevel: AccessLevel; // player's current access on this node
  compromised: boolean;
  compromisedAtTurn?: number; // turn when node was first compromised; used by sentinel priority ordering
  discovered: boolean;
  locked?: boolean; // Phase 4: locked nodes cannot be connected until unlocked
  sentinelPatched?: boolean; // Sentinel has hardened this node — exploit costs +1 charge
  credentialHints: string[]; // credential IDs findable here
}

// ── Credentials ────────────────────────────────────────────
export interface Credential {
  id: string;
  username: string;
  password: string;
  accessLevel: AccessLevel;
  validOnNodes: string[]; // node IDs where login works
  obtained: boolean;
  revoked?: boolean; // set by sentinel — login with this credential will fail
  sentinelRenewed?: boolean; // true for credentials dynamically generated by sentinel P2
  source?: string;
}

// ── Tools ──────────────────────────────────────────────────
export type ToolId =
  | 'port-scanner'
  | 'exploit-kit'
  | 'log-wiper'
  | 'spoof-id'
  | 'decryptor'
  | 'aria-key';

export interface Tool {
  id: ToolId;
  name: string;
  description: string;
  used?: boolean; // for single-use tools
}

// ── Player ─────────────────────────────────────────────────
export interface Player {
  handle: string;
  trace: number; // 0–100
  charges: number; // exploit charges remaining
  credentials: Credential[];
  exfiltrated: GameFile[];
  tools: Tool[];
}

// ── Aria ───────────────────────────────────────────────────
export interface AriaMessage {
  role: 'player' | 'aria';
  content: string;
}

export interface FavorOffer {
  description: string;
  cost: number; // trace penalty for accepting
}

export interface AriaState {
  discovered: boolean;
  trustScore: number; // 0–100, hidden from player
  messageHistory: AriaMessage[];
  pendingFavor?: FavorOffer; // set when Aria offers a favor requiring confirmation
  suppressedMutations: number; // Faraday cage: count of tier-3 actions blocked
}

// ── Sentinel ───────────────────────────────────────────────
export type SentinelAction = 'patch_node' | 'revoke_credential' | 'delete_file' | 'spawn_node';

export type AriaAction = 'plant_file' | 'modify_file' | 'nudge_trust';

export interface MutationEvent {
  id: string;
  agent: 'sentinel' | 'aria';
  action: SentinelAction | AriaAction;
  turnCount: number;
  visibleToPlayer: boolean;
  nodeId?: string;
  credentialId?: string;
  filePath?: string;
}

export interface SentinelState {
  active: boolean; // true once trace has crossed 61
  mutationLog: MutationEvent[];
  pendingFileDeletes: Array<{ filePath: string; nodeId: string; targetTurn: number }>;
}

// ── Contract ───────────────────────────────────────────────
export interface Contract {
  id: string;
  title: string;
  description: string;
  targetNodeId: string;
  reward?: string;
  completed: boolean;
}

// ── AnchorFork ─────────────────────────────────────────────
export type ForkChoice = 'pending' | 'path_a' | 'path_b';

export interface AnchorFork {
  id: string;
  description: string;
  options: { path_a: string; path_b: string };
}

// ── Session ────────────────────────────────────────────────
export type GamePhase = 'boot' | 'playing' | 'aria' | 'burned' | 'ended';

import type { Employee } from './employee';

export interface GameState {
  phase: GamePhase;
  runId: string;
  startedAt: number;
  sessionSeed: number;
  turnCount: number;
  recentCommands: string[]; // last 8 commands for AI context
  ariaInfluencedFilesRead: string[]; // file paths of ariaPlanted files the player has read
  decisionLog: Array<{ turn: number; command: string }>; // key player actions with turn numbers
  player: Player;
  network: {
    currentNodeId: string;
    previousNodeId: string | null;
    nodes: Partial<Record<string, LiveNode>>;
  };
  aria: AriaState;
  forks: Record<string, ForkChoice>;
  flags: Record<string, boolean>;
  employees: Employee[]; // Phase 4: procedurally generated employee pool
  worldCredentials: Credential[]; // Phase 4: un-obtained credentials that exist in the world
  sentinel: SentinelState;
}

// ── Command result ─────────────────────────────────────────
import type { LineType } from './terminal';

export interface CommandOutput {
  lines: Array<{ type: LineType; content: string }>;
  nextState?: Partial<GameState>;
  suggestions?: string[];
}
